server:
  VERSION: "1"
  PORT: 8080
  ENV: "Development"
  jwt:
    REFRESH_COOKIE_NAME: "auth-refresh-token"
    ACCESS_COOKIE_NAME: "auth-access-token"
    REFRESH_EXPIRES_AT: 43200
    ACCESS_EXPIRES_AT: 5
    SECRET_KEY: "secret :)"
database:
  PORT: 5432
  HOST: psql
  NAME: postgres
  USER: postgres
  PSWD: postgres
  DRIVER: postgres
