version: '3.8'
services:
  backend:
    container_name: backend_container
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - psql 
  psql:
    container_name: postgres_container
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped